language: sh
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq zsh mksh pdksh
install: true
script:
- bash ./test
- dash ./test
- ksh ./test
- mksh ./test
- pdksh ./test
- zsh ./test
branches:
    only:
        - master
